// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlVHaYwJqgOKSQ8CSYver2pPlx4pHV5A',
    appId: '1:744959596910:web:fe93c75dd3927ffeea897f',
    messagingSenderId: '744959596910',
    projectId: 'car-fix-up',
    authDomain: 'car-fix-up.firebaseapp.com',
    storageBucket: 'car-fix-up.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArctudyOOHp9lUWyIbVcpSCUI2RttJVoQ',
    appId: '1:744959596910:android:ef42e5ebddd31fbcea897f',
    messagingSenderId: '744959596910',
    projectId: 'car-fix-up',
    storageBucket: 'car-fix-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuG64jIrjk5b9l6OoEm0Ho2zouoSR4VLo',
    appId: '1:744959596910:ios:a278ce1de40430b1ea897f',
    messagingSenderId: '744959596910',
    projectId: 'car-fix-up',
    storageBucket: 'car-fix-up.appspot.com',
    iosBundleId: 'com.example.carFixUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuG64jIrjk5b9l6OoEm0Ho2zouoSR4VLo',
    appId: '1:744959596910:ios:a278ce1de40430b1ea897f',
    messagingSenderId: '744959596910',
    projectId: 'car-fix-up',
    storageBucket: 'car-fix-up.appspot.com',
    iosBundleId: 'com.example.carFixUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGlVHaYwJqgOKSQ8CSYver2pPlx4pHV5A',
    appId: '1:744959596910:web:003824d2981f1c10ea897f',
    messagingSenderId: '744959596910',
    projectId: 'car-fix-up',
    authDomain: 'car-fix-up.firebaseapp.com',
    storageBucket: 'car-fix-up.appspot.com',
  );
}
